### ISSUE TITLE
master needs to be updated

### ISSUE THREAD

**Issue by Jasonface900** [Team-4664-ButlerBots/Robotics-2016-Code-java#6]
### Task List

---
- [ ] Finish drive train code.
- [ ] Finish arm code.
- [ ] Finish camera code. (@YourAverageRandy)
- [ ] Merge drive train code.
- [ ] Merge updated arm code.
- [ ] Merge camera code.
- [ ] Test run code.
